export type IngredientTaxonomyCategory = "Produce" | "Dairy" | "Meat" | "Dry Goods" | "Canned & Jarred" | "Other";

export type IngredientTaxonomyEntry = {
  canonical: string;
  category: IngredientTaxonomyCategory;
  aliases: string[];
};

export const INGREDIENT_TAXONOMY: IngredientTaxonomyEntry[] = [
  { canonical: "apple", category: "Produce", aliases: ["apples"] },
  { canonical: "banana", category: "Produce", aliases: ["bananas"] },
  { canonical: "avocado", category: "Produce", aliases: ["avocados"] },
  { canonical: "lemon", category: "Produce", aliases: ["lemons"] },
  { canonical: "lime", category: "Produce", aliases: ["limes"] },
  { canonical: "orange", category: "Produce", aliases: ["oranges"] },
  { canonical: "grapefruit", category: "Produce", aliases: ["grapefruits"] },
  { canonical: "grape", category: "Produce", aliases: ["grapes"] },
  { canonical: "pear", category: "Produce", aliases: ["pears"] },
  { canonical: "peach", category: "Produce", aliases: ["peaches"] },
  { canonical: "pineapple", category: "Produce", aliases: ["pineapples"] },
  { canonical: "mango", category: "Produce", aliases: ["mangoes", "mangos"] },
  { canonical: "papaya", category: "Produce", aliases: ["papayas"] },
  { canonical: "watermelon", category: "Produce", aliases: ["watermelons"] },
  { canonical: "cantaloupe", category: "Produce", aliases: ["cantaloupes"] },
  { canonical: "strawberry", category: "Produce", aliases: ["strawberries"] },
  { canonical: "blueberry", category: "Produce", aliases: ["blueberries"] },
  { canonical: "raspberry", category: "Produce", aliases: ["raspberries"] },
  { canonical: "blackberry", category: "Produce", aliases: ["blackberries"] },
  { canonical: "onion", category: "Produce", aliases: ["onions", "yellow onion", "red onion", "white onion"] },
  {
    canonical: "shallot",
    category: "Produce",
    aliases: ["shallots", "eschalot", "eschalots", "eschallot", "eschallots", "eshallot", "eshallots"],
  },
  { canonical: "garlic", category: "Produce", aliases: ["garlic clove", "garlic cloves"] },
  { canonical: "ginger", category: "Produce", aliases: ["fresh ginger", "ginger root"] },
  {
    canonical: "green onion",
    category: "Produce",
    aliases: ["green onions", "scallion", "scallions", "spring onion", "spring onions"],
  },
  { canonical: "leek", category: "Produce", aliases: ["leeks"] },
  { canonical: "chive", category: "Produce", aliases: ["chives"] },
  { canonical: "carrot", category: "Produce", aliases: ["carrots"] },
  { canonical: "celery", category: "Produce", aliases: ["celery stalk", "celery stalks"] },
  { canonical: "potato", category: "Produce", aliases: ["potatoes", "russet potato", "yukon gold potato"] },
  { canonical: "sweet potato", category: "Produce", aliases: ["sweet potatoes", "yam", "yams"] },
  { canonical: "tomato", category: "Produce", aliases: ["tomatoes", "roma tomato", "heirloom tomato"] },
  { canonical: "cherry tomato", category: "Produce", aliases: ["cherry tomatoes", "grape tomato", "grape tomatoes"] },
  { canonical: "cucumber", category: "Produce", aliases: ["cucumbers"] },
  { canonical: "zucchini", category: "Produce", aliases: ["zucchinis", "courgette", "courgettes"] },
  { canonical: "eggplant", category: "Produce", aliases: ["eggplants", "aubergine", "aubergines"] },
  { canonical: "bell pepper", category: "Produce", aliases: ["bell peppers", "capsicum", "capsicums"] },
  { canonical: "pepper", category: "Produce", aliases: ["peppers", "red pepper", "green pepper"] },
  { canonical: "jalapeno", category: "Produce", aliases: ["jalapenos", "jalapeno pepper"] },
  { canonical: "serrano pepper", category: "Produce", aliases: ["serrano peppers"] },
  { canonical: "poblano pepper", category: "Produce", aliases: ["poblano peppers"] },
  { canonical: "habanero pepper", category: "Produce", aliases: ["habanero peppers"] },
  { canonical: "chili pepper", category: "Produce", aliases: ["chili peppers", "red chili", "green chili", "chile"] },
  { canonical: "broccoli", category: "Produce", aliases: ["broccoli floret", "broccoli florets"] },
  { canonical: "cauliflower", category: "Produce", aliases: ["cauliflower floret", "cauliflower florets"] },
  { canonical: "cabbage", category: "Produce", aliases: ["green cabbage", "red cabbage"] },
  { canonical: "napa cabbage", category: "Produce", aliases: [] },
  { canonical: "bok choy", category: "Produce", aliases: ["bok choi"] },
  { canonical: "kale", category: "Produce", aliases: [] },
  { canonical: "spinach", category: "Produce", aliases: ["baby spinach"] },
  { canonical: "arugula", category: "Produce", aliases: ["rocket"] },
  { canonical: "lettuce", category: "Produce", aliases: ["leaf lettuce"] },
  { canonical: "romaine lettuce", category: "Produce", aliases: ["romaine"] },
  { canonical: "brussels sprout", category: "Produce", aliases: ["brussels sprouts"] },
  { canonical: "asparagus", category: "Produce", aliases: ["asparagus spear", "asparagus spears"] },
  { canonical: "green bean", category: "Produce", aliases: ["green beans", "haricots verts"] },
  { canonical: "snap pea", category: "Produce", aliases: ["snap peas", "sugar snap pea", "sugar snap peas"] },
  { canonical: "snow pea", category: "Produce", aliases: ["snow peas"] },
  { canonical: "pea", category: "Produce", aliases: ["peas"] },
  { canonical: "corn", category: "Produce", aliases: ["sweet corn", "corn kernel", "corn kernels"] },
  { canonical: "mushroom", category: "Produce", aliases: ["mushrooms", "mixed mushroom", "mixed mushrooms"] },
  { canonical: "shiitake mushroom", category: "Produce", aliases: ["shiitake mushrooms"] },
  { canonical: "portobello mushroom", category: "Produce", aliases: ["portobello mushrooms"] },
  { canonical: "button mushroom", category: "Produce", aliases: ["button mushrooms", "cremini mushroom", "cremini mushrooms"] },
  { canonical: "pumpkin", category: "Produce", aliases: ["pumpkins"] },
  { canonical: "butternut squash", category: "Produce", aliases: [] },
  { canonical: "acorn squash", category: "Produce", aliases: [] },
  { canonical: "radish", category: "Produce", aliases: ["radishes"] },
  { canonical: "beet", category: "Produce", aliases: ["beets", "beetroot"] },
  { canonical: "turnip", category: "Produce", aliases: ["turnips"] },
  { canonical: "fennel", category: "Produce", aliases: ["fennel bulb"] },
  { canonical: "parsley", category: "Produce", aliases: ["flat leaf parsley", "italian parsley"] },
  { canonical: "cilantro", category: "Produce", aliases: ["coriander leaves", "fresh coriander"] },
  { canonical: "basil", category: "Produce", aliases: ["thai basil", "fresh basil"] },
  { canonical: "mint", category: "Produce", aliases: ["fresh mint"] },
  { canonical: "dill", category: "Produce", aliases: ["fresh dill"] },
  { canonical: "thyme", category: "Produce", aliases: ["fresh thyme"] },
  { canonical: "rosemary", category: "Produce", aliases: ["fresh rosemary"] },
  { canonical: "oregano", category: "Produce", aliases: ["fresh oregano"] },
  { canonical: "sage", category: "Produce", aliases: ["fresh sage"] },

  { canonical: "milk", category: "Dairy", aliases: ["whole milk", "skim milk", "2 milk"] },
  { canonical: "heavy cream", category: "Dairy", aliases: ["double cream", "whipping cream"] },
  { canonical: "half and half", category: "Dairy", aliases: ["half half"] },
  { canonical: "butter", category: "Dairy", aliases: ["unsalted butter", "salted butter"] },
  { canonical: "ghee", category: "Dairy", aliases: ["clarified butter"] },
  { canonical: "cheese", category: "Dairy", aliases: ["shredded cheese"] },
  { canonical: "parmesan cheese", category: "Dairy", aliases: ["parmesan", "parmigiano reggiano"] },
  { canonical: "mozzarella cheese", category: "Dairy", aliases: ["mozzarella"] },
  { canonical: "cheddar cheese", category: "Dairy", aliases: ["cheddar"] },
  { canonical: "feta cheese", category: "Dairy", aliases: ["feta"] },
  { canonical: "goat cheese", category: "Dairy", aliases: ["chevre"] },
  { canonical: "cream cheese", category: "Dairy", aliases: [] },
  { canonical: "sour cream", category: "Dairy", aliases: [] },
  { canonical: "yogurt", category: "Dairy", aliases: ["plain yogurt"] },
  { canonical: "greek yogurt", category: "Dairy", aliases: [] },
  { canonical: "buttermilk", category: "Dairy", aliases: [] },
  { canonical: "egg", category: "Dairy", aliases: ["eggs"] },

  { canonical: "chicken", category: "Meat", aliases: ["chicken breast", "chicken thigh", "chicken thighs"] },
  { canonical: "beef", category: "Meat", aliases: ["ground beef", "beef chuck", "beef roast"] },
  { canonical: "steak", category: "Meat", aliases: ["sirloin steak", "ribeye steak"] },
  { canonical: "pork", category: "Meat", aliases: ["pork loin", "pork shoulder", "pork chop", "pork chops"] },
  { canonical: "bacon", category: "Meat", aliases: [] },
  { canonical: "sausage", category: "Meat", aliases: ["italian sausage", "breakfast sausage"] },
  { canonical: "lamb", category: "Meat", aliases: ["lamb chop", "lamb chops"] },
  { canonical: "turkey", category: "Meat", aliases: ["ground turkey"] },
  { canonical: "duck", category: "Meat", aliases: ["duck breast"] },
  { canonical: "ham", category: "Meat", aliases: [] },
  { canonical: "prosciutto", category: "Meat", aliases: [] },
  { canonical: "fish", category: "Meat", aliases: ["white fish"] },
  { canonical: "salmon", category: "Meat", aliases: ["salmon fillet", "salmon filet"] },
  { canonical: "tuna", category: "Meat", aliases: ["tuna steak"] },
  { canonical: "cod", category: "Meat", aliases: ["cod fillet", "cod filet"] },
  { canonical: "tilapia", category: "Meat", aliases: ["tilapia fillet", "tilapia filet"] },
  { canonical: "shrimp", category: "Meat", aliases: ["prawn", "prawns"] },
  { canonical: "scallop", category: "Meat", aliases: ["scallops"] },
  { canonical: "crab", category: "Meat", aliases: ["crab meat"] },
  { canonical: "lobster", category: "Meat", aliases: ["lobster tail", "lobster tails"] },
  { canonical: "anchovy", category: "Meat", aliases: ["anchovies"] },
  { canonical: "sardine", category: "Meat", aliases: ["sardines"] },

  { canonical: "olive oil", category: "Dry Goods", aliases: ["extra virgin olive oil"] },
  { canonical: "vegetable oil", category: "Dry Goods", aliases: [] },
  { canonical: "canola oil", category: "Dry Goods", aliases: [] },
  { canonical: "sesame oil", category: "Dry Goods", aliases: [] },
  { canonical: "coconut oil", category: "Dry Goods", aliases: [] },
  { canonical: "flour", category: "Dry Goods", aliases: ["all purpose flour", "plain flour"] },
  { canonical: "bread flour", category: "Dry Goods", aliases: [] },
  { canonical: "whole wheat flour", category: "Dry Goods", aliases: [] },
  { canonical: "almond flour", category: "Dry Goods", aliases: [] },
  { canonical: "sugar", category: "Dry Goods", aliases: ["white sugar", "granulated sugar"] },
  { canonical: "brown sugar", category: "Dry Goods", aliases: ["light brown sugar", "dark brown sugar"] },
  { canonical: "powdered sugar", category: "Dry Goods", aliases: ["confectioners sugar", "icing sugar"] },
  { canonical: "salt", category: "Dry Goods", aliases: ["table salt"] },
  { canonical: "kosher salt", category: "Dry Goods", aliases: [] },
  { canonical: "sea salt", category: "Dry Goods", aliases: [] },
  { canonical: "black pepper", category: "Dry Goods", aliases: ["ground black pepper", "peppercorn"] },
  { canonical: "white pepper", category: "Dry Goods", aliases: [] },
  { canonical: "rice", category: "Dry Goods", aliases: ["white rice", "long grain rice"] },
  { canonical: "jasmine rice", category: "Dry Goods", aliases: [] },
  { canonical: "basmati rice", category: "Dry Goods", aliases: [] },
  { canonical: "pasta", category: "Dry Goods", aliases: ["dry pasta"] },
  { canonical: "spaghetti", category: "Dry Goods", aliases: [] },
  { canonical: "noodle", category: "Dry Goods", aliases: ["noodles", "ramen noodles"] },
  { canonical: "quinoa", category: "Dry Goods", aliases: [] },
  { canonical: "oat", category: "Dry Goods", aliases: ["oats", "rolled oats"] },
  { canonical: "breadcrumb", category: "Dry Goods", aliases: ["breadcrumbs"] },
  { canonical: "panko", category: "Dry Goods", aliases: ["panko breadcrumb", "panko breadcrumbs"] },
  { canonical: "chicken stock", category: "Canned & Jarred", aliases: ["chicken broth"] },
  { canonical: "vegetable stock", category: "Canned & Jarred", aliases: ["vegetable broth"] },
  { canonical: "beef stock", category: "Canned & Jarred", aliases: ["beef broth"] },
  { canonical: "tomato paste", category: "Canned & Jarred", aliases: [] },
  { canonical: "tomato sauce", category: "Canned & Jarred", aliases: [] },
  { canonical: "canned tomato", category: "Canned & Jarred", aliases: ["canned tomatoes", "diced tomatoes", "crushed tomatoes"] },
  { canonical: "bean", category: "Canned & Jarred", aliases: ["beans"] },
  { canonical: "black bean", category: "Canned & Jarred", aliases: ["black beans"] },
  { canonical: "kidney bean", category: "Canned & Jarred", aliases: ["kidney beans"] },
  { canonical: "cannellini bean", category: "Canned & Jarred", aliases: ["cannellini beans", "white beans"] },
  { canonical: "chickpea", category: "Canned & Jarred", aliases: ["chickpeas", "garbanzo bean", "garbanzo beans"] },
  { canonical: "lentil", category: "Dry Goods", aliases: ["lentils"] },
  { canonical: "soy sauce", category: "Dry Goods", aliases: ["tamari"] },
  { canonical: "fish sauce", category: "Dry Goods", aliases: [] },
  { canonical: "oyster sauce", category: "Dry Goods", aliases: [] },
  { canonical: "hoisin sauce", category: "Dry Goods", aliases: [] },
  { canonical: "worcestershire sauce", category: "Dry Goods", aliases: [] },
  { canonical: "hot sauce", category: "Dry Goods", aliases: ["chili sauce"] },
  { canonical: "salsa", category: "Canned & Jarred", aliases: [] },
  { canonical: "mustard", category: "Dry Goods", aliases: ["yellow mustard"] },
  { canonical: "dijon mustard", category: "Dry Goods", aliases: [] },
  { canonical: "mayonnaise", category: "Dry Goods", aliases: ["mayo"] },
  { canonical: "ketchup", category: "Dry Goods", aliases: ["catsup"] },
  { canonical: "vinegar", category: "Dry Goods", aliases: [] },
  { canonical: "apple cider vinegar", category: "Dry Goods", aliases: ["cider vinegar"] },
  { canonical: "red wine vinegar", category: "Dry Goods", aliases: [] },
  { canonical: "white wine vinegar", category: "Dry Goods", aliases: [] },
  { canonical: "balsamic vinegar", category: "Dry Goods", aliases: [] },
  { canonical: "rice vinegar", category: "Dry Goods", aliases: [] },
  { canonical: "honey", category: "Dry Goods", aliases: [] },
  { canonical: "maple syrup", category: "Dry Goods", aliases: [] },
  { canonical: "peanut butter", category: "Dry Goods", aliases: [] },
  { canonical: "almond butter", category: "Dry Goods", aliases: [] },
  { canonical: "coconut milk", category: "Canned & Jarred", aliases: [] },
  { canonical: "almond milk", category: "Dry Goods", aliases: [] },
  { canonical: "evaporated milk", category: "Canned & Jarred", aliases: [] },
  { canonical: "baking powder", category: "Dry Goods", aliases: [] },
  { canonical: "baking soda", category: "Dry Goods", aliases: [] },
  { canonical: "cornstarch", category: "Dry Goods", aliases: ["corn starch"] },
  { canonical: "cocoa powder", category: "Dry Goods", aliases: [] },
  { canonical: "vanilla extract", category: "Dry Goods", aliases: [] },
  { canonical: "cinnamon", category: "Dry Goods", aliases: ["ground cinnamon"] },
  { canonical: "cumin", category: "Dry Goods", aliases: ["ground cumin"] },
  { canonical: "paprika", category: "Dry Goods", aliases: ["smoked paprika"] },
  { canonical: "chili powder", category: "Dry Goods", aliases: ["chilli powder"] },
  { canonical: "curry powder", category: "Dry Goods", aliases: [] },
  { canonical: "turmeric", category: "Dry Goods", aliases: ["ground turmeric"] },
  { canonical: "bay leaf", category: "Dry Goods", aliases: ["bay leaves"] },
  { canonical: "yeast", category: "Dry Goods", aliases: ["active dry yeast", "instant yeast"] },
  { canonical: "tortilla", category: "Dry Goods", aliases: ["tortillas", "corn tortilla", "flour tortilla"] },
  { canonical: "coconut flake", category: "Dry Goods", aliases: ["coconut flakes", "shredded coconut"] },
];
